### ISSUE TITLE
Kết nối lại

### ISSUE THREAD

**Issue by khacpv** [khacpv/altp#46]
gửi trả lại room + users

**Comment by khacpv** [comment]
trả lời trong khi & trước khi mất kết nối

**Comment by hantrungkien** [comment]
1. Chưa trả lời đã mất kết nối => OK
2. Trả lời rồi nhưng đối phương chưa trả lời thì mất kết nối => OK
3. Trả lời rồi và đối phương cũng trả lời rồi thì mất kết nối => 
   - trường hợp cả 2 người đều trả lời đúng => server đã đẩy câu hỏi tiếp theo, tuy có kết nối lại nhưng gửi trả lời của câu cũ
   - trường hợp gameover cũng vậy. 
     3 chưa OK

**Comment by khacpv** [comment]
ok
